#!/usr/bin/env bash
#Set Internal Field Separator (IFS) to ':'
IFS=':'

# Read each line of /etc/passwd file
while read -r username password userid groupid userinfo homedir shell; do
    # Display the information in the required format
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd
