#!/usr/bin/env bash
# This script tells a story about users from /etc/passwd

while IFS=: read -r username _ user_id _ _ home_dir shell user_info; do
    echo "The user $username is part of the $user_id gang, lives in $home_dir and rides $shell. $user_id's place is protected by the passcode x, more info about the user here: $user_info"
done < /etc/passwd
