#!/usr/bin/env bash
#This script displays 'Best School' 10 times using a while loop
count=1  # Initialize a counter

while [ $count -le 10 ]  # Continue until the counter is greater than 10
do
	    echo "Best School"  # Display the message
	        ((count++))  # Increment the counter
	done
