#!/usr/bin/env bash
#This script gives information about the 'school' file

if [ -e "school" ]; then  # Check if the file exists
    echo "school file exists"
    
    if [ -s "school" ]; then  # Check if the file is not empty
        echo "school file is not empty"
    else  # If the file is empty
        echo "school file is empty"
    fi
    
    if [ -f "school" ]; then  # Check if the file is a regular file
        echo "school is a regular file"
    fi

else  # If the file does not exist
    echo "school file does not exist"
fi
