#!/usr/bin/env bash
# 11-manage_my_process - Manage the manage_my_process script

if [[ "$#" == "1" ]]; then
    if [[ "$1" == "start" ]]; then
        if test -f "/var/run/my_process.pid"; then
            echo "manage_my_process is already running"
        else
            ./manage_my_process &
            echo "$!" > /var/run/my_process.pid
            echo "manage_my_process started"
        fi

    elif [[ "$1" == "stop" ]]; then
        if test -f "/var/run/my_process.pid"; then
            kill "$(cat /var/run/my_process.pid)"
            rm  -f /var/run/my_process.pid
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running"
        fi

    elif [[ "$1" == "restart" ]]; then
        # Stop program
        if test -f "/var/run/my_process.pid"; then
            kill "$(cat /var/run/my_process.pid)"
            rm /var/run/my_process.pid
        fi

        # Start program
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process restarted"

    else
        echo "Usage: manage_my_process {start|stop|restart}"
    fi
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
