#!/usr/bin/env bash
# 11-manage_my_process - Manages the manage_my_process script

PID_FILE="/var/run/my_process.pid"

if [[ "$#" == "1" ]]; then
    if [[ "$1" == "start" ]]; then
        if test -f "$PID_FILE"; then
            echo "manage_my_process is already running"
        else
            ./manage_my_process &  # Start the process in the background
            echo "$!" > "$PID_FILE"  # Save the process ID to the pid file
            echo "manage_my_process started"
        fi

    elif [[ "$1" == "stop" ]]; then
        if test -f "$PID_FILE"; then
            kill "$(cat "$PID_FILE")"  # Kill the process using the PID from the file
            rm "$PID_FILE"  # Remove the PID file after stopping the process
            echo "manage_my_process stopped"
        else
            echo "No running instance of manage_my_process found."
        fi

    elif [[ "$1" == "restart" ]]; then
        # Stop the process if running
        if test -f "$PID_FILE"; then
            kill "$(cat "$PID_FILE")"  # Stop the process
            rm "$PID_FILE"  # Remove the PID file
        fi
        # Start the process again
        ./manage_my_process &  # Start the process in the background
        echo "$!" > "$PID_FILE"  # Save the new process ID to the pid file
        echo "manage_my_process restarted"

    else
        echo "Usage: manage_my_process {start|stop|restart}"
    fi
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi

